### ISSUE TITLE
Add Use Cases for Unique Selling Point

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#104]
Use cases for:

- [x] Route planning
- [x] Dynamic route adjustment
- [x] Live-navigation
- [x] Smart delay calculation

Optional:

- [ ] Review those use cases and specify them, if needed

Maybe think about some more scenarios for use cases, if needed

**Comment by AconexOfficial** [comment]
Time spent: 2 hours 30 minutes
