### ISSUE TITLE
Project Vision: Work out contents.

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#145]
- [x] develop concept
- [x] discuss concept
- [x] refine concept
- [x] work out content
- [x] provide a link for finished presentation in github (Wiki)

Link for presentation in discord

**Comment by LaraBiss** [comment]
Time spent: 2 hours 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 7 hours

**Comment by LaraBiss** [comment]
Time spent: 6 hours

**Comment by JaJako** [comment]
Time spent: 1 hours 30 minutes

**Comment by JaJako** [comment]
Time spent: 30 minutes

**Comment by JaJako** [comment]
@Oeffis/core-team Do we want to link the presentation from today on GitHub (e.g. in our Wiki)? Otherwise the final task of this issue can be removed/changed to "on Discord" and the issue itself be closed.

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes
