### ISSUE TITLE
Types returned by journeys backend should be independent of API used

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#155]
The "journey"/"trip" module in backend depends on a 3rd party library that's being used to plan a journey. This 3rd party library returns it's own types. This types should not be transferred to frontend - frontend should be independent of any 3rd party library which is likely to change over time. (For now _vrr_client_ is being used as 3rd party library.)
To achieve this, a custom "type layer" has to be defined in backend that defines all types we want to use within our app. 3rd party specific types are being converted to our custom types.

Steps:
- [x] Define custom types/dtos for ~Stops~ Locations
- [x] Implement converter for ~Stops~ Locations (vrr_client type -> custom type)
- [x] Define custom types/dtos for Trips
- [x] Implement converter/mapper for Trips (vrr_client type -> custom type)
- [x] Re-Generate frontend API files
- [x] Adjust dependent frontend parts (e.g. journeyDemo)

**Comment by JaJako** [comment]
When all 3rd party types are removed, "@types/hafas-client" should be removed from frontend dependencies.

**Comment by timvahlbrock** [comment]
There seems to be a EU wide specification called transmodel, which is used by the rail providers of the european countries to share PT information with each other, see https://www.transmodel-cen.eu/ . Maybe we can build our types as a subset of those.

**Comment by timvahlbrock** [comment]
@JaJako if I understand correctly, FPTF is more of a "loose" standard, which is shared between multiple hafas client libraries, isn't it?

**Comment by JaJako** [comment]
> There seems to be a EU wide specification called transmodel, which is used by the rail providers of the european countries to share PT information with each other, see https://www.transmodel-cen.eu/ . Maybe we can build our types as a subset of those.

That's looking interesting indeed. As far as I unterstand there's a german variant in use already: https://www.vdv.de/ist-daten-schnittstellen-en.aspx . The question is how much overhead will be generated when trying to adapt our types (mainly time wise).

**Comment by JaJako** [comment]
> @JaJako if I understand correctly, FPTF is more of a "loose" standard, which is shared between multiple hafas client libraries, isn't it?

Yes, it´s an open source formalization or simplification of an format you can use in your own PT project if you like (so you don´t need to start by zero creating your own types) - at leasts that's how I would evaluate it. At least it states to be "conceptually inspired by the de-facto standard [GTFS](https://developers.google.com/transit/gtfs/)". But FPTF is no "official" format/standard.

**Comment by JaJako** [comment]
Time spent: 1 hour 30 minutes

First look at the current implementation/types together and planning of how to address the issue.

**Comment by JaJako** [comment]
Time spent: 2 hours

Proposal of definitions for types.

**Comment by JaJako** [comment]
Time spent: 30 minutes

Discussing proposal and further working process.

**Comment by JaJako** [comment]
Time spent: 2 hours

Introducing custom types for stop (now named location) in Backend.

**Comment by dkrakau** [comment]
Time spent: 1 hour 30 minutes

**Comment by dkrakau** [comment]
Time spent: 30 minutes

**Comment by dkrakau** [comment]
Time spent: 2 hours

**Comment by JaJako** [comment]
Time spent: 2 hours 30 minutes

Further type adjustment and changes in frontend.

**Comment by JaJako** [comment]
Time spent: 2 hours

Rebasing onto main and fixing problems.

**Comment by JaJako** [comment]
Time spent: 3 hours

Implementing Feedback from Review and trying to solve problems with enum types.

**Comment by JaJako** [comment]
Time spent: 1 hour

Fixed realtimeStatus not being mapped, undefined handling and added handling of departure/arrival after rebase onto main.

**Comment by JaJako** [comment]
Time spent: 30 minutes

Resolving issues with passing Dates from Frontend to Backend (departure time).
