### ISSUE TITLE
Set up Repo/Project

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#16]
Configuring git/repo and setting up the project.

- [x] Bootstrap Frontend
- [x] Bootstrap Backend
- [x] #19
- [x] #20
- [x] #21
- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #31
- [ ] #106 

## Additional

- [x] #30

**Comment by timvahlbrock** [comment]
@core-team members each needs to add the time spent on this issue.

**Comment by Paulomart** [comment]
Time spent: 6 hours

**Comment by JaJako** [comment]
Time spent: 6 hours

**Comment by Escowei98** [comment]
Time spent: 6 hours

**Comment by JaJako** [comment]
Time spent: 1 hour

Fixes local problems with symlinks and windows (even if it may not has been the problem that caused a "not found" error on an package import of oeffis/vrr_client).

**Comment by JaJako** [comment]
Time spent: 30 minutes

Updating webstorm launch configs (to vscode launch configs' state).

**Comment by AconexOfficial** [comment]
Time spent: 6 hours

**Comment by AconexOfficial** [comment]
Time spent: 2 hours

**Comment by timvahlbrock** [comment]
Last point is a continuous todo

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by LaraBiss** [comment]
Time spent: 6 hours
