### ISSUE TITLE
replace HAFAS-API-usages in Backend with VRR-Api

### ISSUE THREAD

**Issue by Escowei98** [Oeffis/Oeffis#173]

**Comment by Paulomart** [comment]
Time spent: 3 hours

**Comment by timvahlbrock** [comment]
Time spent: 2 hours

Spent on:

- Prototyping, dismissed (#199)

**Comment by timvahlbrock** [comment]
Time spent: 3 hours

Spent on:
+ 03bb2d8d958f8d3948a99af3bfdd89e295f76129 fix linting errors
+ 894628327f0bdb3511c9f2f2110ecf3a3535b466 create second endpoint to query locations by name, fix tests, disallow dangling commas
+ a63b257d8499cf23786a22b3efe0553275442515 improve stop mapping
+ de3d2a2bf944fb9225ceb473ad82d9ae539a81de add endpoint for trip query
+ 0959088a4766cf4c868972ad151f3d0c3b18a78f fix linting errors
+ d3c4c9948f60c24da2df49859591da6eb4adbb30 adapt frontend to backend changes

**Comment by timvahlbrock** [comment]
Time spent: 30 minutes

Spent on:

+ a1acca4 fix some test errors
+ d68719a fix tests

**Comment by timvahlbrock** [comment]
Time spent: 1 hours

Spent on:
- fixing the CI configuration
