### ISSUE TITLE
Create UCs for Milestone Dynamic Route adjustment

### ISSUE THREAD

**Issue by Escowei98** [Oeffis/Oeffis#177]

**Comment by JaJako** [comment]
Time spent: 30 minutes

Created issues for UCs listed on Wiki and added some subtasks that are needed to fulfill each UC.

**Comment by JaJako** [comment]
Time spent: 1 hour

Further refinement of UCs, needed subtasks and dependencies among themselves.

**Comment by JaJako** [comment]
Before starting work on this milestone's behalf, the UCs should get reviewed/discussed all together. Will be tracked in: #208
