### ISSUE TITLE
Accelerate docker builds

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#180]
Currently, each container arch builds its own version of the web assets, in addition to the ones build by the build/lint job. As this takes very long on arm64 (due to emulation) we should think about moving out of the arm emulation. We currently see two options:

1. build in an amd64 image beforehand and copy to the target arches
2. upload the build artefacts in the build step and download them in the container stage

**Comment by timvahlbrock** [comment]
New (most clean way): make ARM docker build optional/lazy.

**Comment by timvahlbrock** [comment]
Time Spent: 1 hours

Spent on:

+ 6e4fefe81bf4e4ffa7aa5441d2a921411cec3566 move arm builds to own (optional) build step
+ 1d4e075ff3c64dcc61edf18936ae62efbcfd6c08 improve build container step naming

**Comment by Paulomart** [comment]
Time spent: 30 minutes

Review; Fixes;

**Comment by Paulomart** [comment]
This is still an issue. Working on it now.

**Comment by Paulomart** [comment]
Timespent: 1 hour

* #197

**Comment by Paulomart** [comment]
Time spent: 1 hour

* #197
