### ISSUE TITLE
Documentation: How to track time

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#19]
- [x] Wiki Entry: How to do time tracking
- [x] Ensure automatic aggregation is possible

**Comment by Paulomart** [comment]
Time spent to far: 1 hour

**Comment by Paulomart** [comment]
See here: https://github.com/Oeffis/Oeffis/wiki/Time-Tracking

**Comment by timvahlbrock** [comment]
Proposal: wrap the statement into a code block, to make it stand out.

**Comment by timvahlbrock** [comment]
>Proposal: wrap the statement into a code block, to make it stand out.
maybe even with a custom "invalid" language tag like time or so

**Comment by Paulomart** [comment]
For the ease of parsing I would like to keep it as is.

**Comment by Paulomart** [comment]
Update: I now think its better to just use `Time spent: xx` as prefix as `so far` could lead to some misinterpretations.

**Comment by Paulomart** [comment]
Time spent: 1 hours
