### ISSUE TITLE
Decisionmaking Route Progress visualization

### ISSUE THREAD

**Issue by Escowei98** [Oeffis/Oeffis#195]

**Comment by AconexOfficial** [comment]
Time spent: 1 hour 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 1 hour 30 minutes

**Comment by dkrakau** [comment]
Time spent: 1 hour 30 minutes

**Comment by AconexOfficial** [comment]
Made decisions are noted one the figma page: https://www.figma.com/file/O7dJ1NyevhYLitnOwRnI6M/Mobile-Prototyp?type=design&node-id=0%3A1&mode=design&t=o46Hid3r4oEplOiz-1

**Comment by timvahlbrock** [comment]
This Issue is marked in state "Done", but still open. Please update it accordingly.
