### ISSUE TITLE
Meeting about general design structure

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#203]
- [x] Guidelines for priorisation and design usage (icons? text?)
- [x] Which components do we use? Which ionic components?
- [x] Find a way to make route planning UI intuitive and simple
- [x] Find date for specific design structure meeting

**Comment by AconexOfficial** [comment]
Time spent: 2 hours 30 minutes

**Comment by Escowei98** [comment]
Time spent: 2 hours 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 2 hours 30 minutes

**Comment by dkrakau** [comment]
Time spent: 2 hours 30 minutes
