### ISSUE TITLE
Meeting about specific component design structure

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#204]
**Meeting 1**
Discussed:

- [x] What are components, what are pages?
- [x] All components listed
- [x] Styling the base components from ionic

**Meeting 2** (soon)
Following points will be discussed in a follow-up meeting after creating the base components:
- [ ] How to sort components inside a parent component? When buttons? When inputs?
- [ ] Style ionic components
  - [ ] Padding
  - [ ] Borders / Corners
  - [ ] Sorting of subcomponents
- [ ] Select used icons

**Comment by AconexOfficial** [comment]
Time spent: 3 hours 30 minutes

**Comment by dkrakau** [comment]
Time spent: 3 hours 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 4 hours

**Comment by dkrakau** [comment]
Time spent: 4 hours
