### ISSUE TITLE
Create wireframe for live-navigation

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#205]
- [ ] decide how to display travel progress
- [ ] option to switch to a faster route
- [ ] cancel live navigation

**Comment by AconexOfficial** [comment]
Time spent: 1 hour 30 minutes

Thought about display possibilities and created two drafts for live navigation wireframes

**Comment by LaraBiss** [comment]
Time spent: 2 hours

Spend on:
- creating alternative examples for live navigation wireframes based on existing wireframes
- added cancel button and dialog

**Comment by AconexOfficial** [comment]
Time spent: 1 hour 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 1 hour 30 minutes

Spend on: 
- discussion & adjustments
