### ISSUE TITLE
UC: Show probabilities of a delay happening (based on past user train data)

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#210]
Summary
The app should show the routes with a special rating, percentage or color to represent the calculated probabilities and occurrences of delays based on historical user data.

Subtasks

- [ ] Get user train data
- [ ] Calculate delays and optimal arrivals
- [ ] Create algorithm to calculate delay probabilities
- [ ] Display probabilities for the route

**Comment by JaJako** [comment]
Using past user data wont get implemented anymore.
