### ISSUE TITLE
UC: Show a recommended (non-optimal?) route based on smart delay calculation and user preferences combined

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#215]
Summary
The app should be able to combine both the smart delay calculation aswell as other user preferences. Both integrated into one system should show the best possible routes aswell as the fastest / most comfortable (least stops/least full/least train changes?)

Subtasks

- [ ] Get user preferences
- [ ] Get train delay possibilities
- [ ] Create algorithm to combine both of them
- [ ] Display the routes by rating them in regard to the combined calculation

**Comment by JaJako** [comment]
No direct recommandations, but more stats to "empower" user to be able to make a good decision.
