### ISSUE TITLE
IDE Launch Configurations (aka npm run ...)

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#22]
- [x] Starting backend
- [x] Starting frontend
~~- [ ] Installing dependencies~~
- [x] add workspace extension recommendations

**Comment by timvahlbrock** [comment]
Installing dependencies shouldn't be task of IDE integration. To automate the user could install a fitting extension other we setup a tool like hus. For now we can install dependencies manually.

**Comment by JaJako** [comment]
IDE-wise, what´s our approach in general? Everyone uses the IDE he/she likes to use or is there a special advantage in using vscode? Or in other words, everyone can contribute IDE-specific configs that are based on the vscode ones?

**Comment by timvahlbrock** [comment]
In principle, choose the IDE you want. Currently I only added ide configuration for VSCode, because I had the impression that the majority of the team used VSCode. But adding for example Idea configuration files should be pretty straightforward.

**Comment by timvahlbrock** [comment]
Time spent: 2 hours
