### ISSUE TITLE
Make user input for start and destination open up a modal with a text input and a selectable list

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#224]

**Comment by timvahlbrock** [comment]
Time spent: 30 minutes

Spent on:
+ Creating PR
+ 16528707f745520f27a6c81ffaf880e94ffc4a3e add empty modal that opens when start is clicked
+ 5aef15dd7233b6bda7fb1462c1f4e854863d5e9b add basic structure to modal

**Comment by Paulomart** [comment]
I will try to continue on this.

**Comment by Paulomart** [comment]
Time spent: 2 hours

**Comment by Paulomart** [comment]
Time spent: 30 minutes

Try to figure out e2e tests...

**Comment by Paulomart** [comment]
Time spent: 30 minutes

Cleanup hook

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

Spent on:

+ 1c38cece8b61ec398a8122d27023a0ad781c9b0f remove trivial 'isReachable' e2e test
+ e4b4d2e3181dafbd9441d06bd5150262ccd277c6 get e2e tests back running for route planner
+ 40a258c8d7a60c91646854d9f2b0cb0fb599ac3c add new tests for routePlanner
+ 9f4a42f31976adf38fbae135ee9e213495d6aa51 improve styling of route planner

**Comment by timvahlbrock** [comment]
Time spent: 1 hour
Spent on: 
+ bbf0280a52edcaa56082e987d028fd85695a0980 add test for destination input
+ dc464202db9e23240135309f51610a2043f8b0cf add test for destination input
+ 1fba85fe6848aedcabf5006cacc35f33abcc3e41 fix ionic input label warning
+ 248c6128804fa2d68feb5e0ab54300ddaf0c2a40 try workaround for cypress-testing-library bug

**Comment by Paulomart** [comment]
Time spent: 30 Minutes

Review and fixes
