### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#23]
- [x] How to start the project (blocked by #22)
- [x] Dependencies
- [x] Contact Information
- [x] License (blocked by #31)
- [x] About the project

**Comment by LaraBiss** [comment]
Time spent: 3,5 hours

**Comment by Paulomart** [comment]
@LaraBiss please try tracking again

**Comment by LaraBiss** [comment]
Time spent: 3.5 hours

**Comment by LaraBiss** [comment]
@Paulomart I think the format should be correct now but got no answer

**Comment by Paulomart** [comment]
Time spent: 3.5 hours

**Comment by LaraBiss** [comment]
Time spent: 3 hours 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 3 hours 30 minutes

**Comment by timvahlbrock** [comment]
The root readme says to run `npm install` in the root directory. This won´t work, as there is no package.json there.
