### ISSUE TITLE
Automatic Validation of ESLint Rules (GitHub Actions)

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#24]
- [ ] Run Linter as part of CI

**Comment by timvahlbrock** [comment]
updated description as the previous requirements were more fitting to #20

**Comment by Paulomart** [comment]
@timvahlbrock is 

>  Run Linter as part of CI

also done?

**Comment by timvahlbrock** [comment]
yes

**Comment by timvahlbrock** [comment]
Time spent: 0 hours

Reason: was resolved by issue #37
