### ISSUE TITLE
Sort searched locations by given score

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#266]
Currently all locations that are returned as search result by vrr api are in no useful order. But the vrr results supply a "matchingQuality"; as higher as this number is, the better the search result should be. 
The search result should get ordered in Backend by the matchingQuality before passed to Frontend.

Depends on types introduced by #155.

**Comment by Paulomart** [comment]
The website of the vrr uses these parameters to query their api:

| Query Param | Query Value |
| -- | -- |
convertAddressesITKernel2LocationServer | 1
convertCoord2LocationServer | 1
convertCrossingsITKernel2LocationServer | 1
convertPOIsITKernel2LocationServer | 1
convertStopsPTKernel2LocationServer | 1
coordOutputFormat | WGS84[dd.ddddd]
doNotSearchForStops_sf | 1
language | de
locationInfoActive | 1
locationServerActive | 1
name_sf | gelsenkirche
outputFormat | rapidJSON
serverInfo | 1
sl3plusStopFinderMacro | trip
type_sf | any
version | 10.5.17.3
vrrStopFinderMacro | 1

**Comment by Paulomart** [comment]
Time spent: 1 hour

* Research into vrr api
* Creating code changes #271
