### ISSUE TITLE
Replace string types with enum types.

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#270]
VRR is using enums at some parts. Currently our types are using strings there as there seems to be problems mapping from one enum to another identical enum.

Probably the best/easiest solution is using one big switch statement to sort out which value of the VRR enum is mapped to which value of our custom enum (which does not necessarily need to be identical to the VRR one). 

Swagger/OpenAPI is supplying the field "enum" instead of "type" inside the @ApiProperty to define that the API is requesting/returning an enum value.

**Comment by Paulomart** [comment]
Time spent: 1 hour

**Comment by JaJako** [comment]
Time spent: 30 minutes

Reviewing changes.

**Comment by Paulomart** [comment]
Time spent: 2 hours

* Fixing module imports
* Figuring out why tests are failing
