### ISSUE TITLE
Automatic Builds (Frontend + Backend) (GitHub Actions)

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#28]
~~- [ ] Set a package name for Android and iOS Platform~~
~~- [ ] Create organisation for Google Play (can be delayed until release)~~
~~- [ ] Create organization for App Store (is required now to create signed iOS bundles)~~
- [x] Create Organization on DockerHub
- [x] Automate Frontend (~~apk and iOS generation~~, PWA Deployment)
- [x] Automate Backend (Docker Image publication)

**Comment by timvahlbrock** [comment]
I can start this task, but we have still some prerequisites to fulfil. I added them to the description.

**Comment by timvahlbrock** [comment]
Due to the increase in tasks, I increased the planned hour from 4 to 10

**Comment by timvahlbrock** [comment]
Both, Google and Apple require Payment to enter their developer program. We need to discuss how we (and maybe if) we want to raise this.

**Comment by timvahlbrock** [comment]
> Both, Google and Apple require Payment to enter their developer program. We need to discuss how we (and maybe if) we want to raise this.

Alternative: Limitation to desktop/PWA release for now

**Comment by Paulomart** [comment]
> PWA

👍

**Comment by timvahlbrock** [comment]
opened a poll. see https://github.com/Oeffis/Oeffis/discussions/62

**Comment by timvahlbrock** [comment]
I created a docker hub organisation https://hub.docker.com/orgs/oeffis/

If anyone wants to be added, I need their docker hub user ids.

I also applied us for the docker open source program.

**Comment by Paulomart** [comment]
@timvahlbrock We can store our docker images on github. [Docker Hub has been turning away from OpenSource for a while now](https://www.heise.de/news/Docker-Hub-streicht-kostenloses-Angebot-Open-Source-Projekte-muessen-handeln-7547959.html). 

> @Paulomart thoughts on deploying PWA? Docker Image?

The best way is to create a docker image and then deploy it like our backend.

**Comment by Paulomart** [comment]
> Well. The action was reverted. We actually are on free tier right now and are even getting some more benefits. But I'm fine with GitHub Image Storage too, just thought docker hub would be more known to most users

We also can publish to both registrys.

> Also: which http-server can you recommend for the frontend docker image?

nginx.

**Comment by timvahlbrock** [comment]
Time spent: 3 hours

**Comment by Paulomart** [comment]
Time spent: 30 minutes

**Comment by timvahlbrock** [comment]
Time spent: 2 hours
