### ISSUE TITLE
Deployment Setup for Kubernetes

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#29]
- [ ] Optional fixes to make application deployable
- [x] Provide a way to run the app in kubernetes

**Comment by timvahlbrock** [comment]
Time spent: 2,5 hours

Spent on:
- adding the possibility to set the backendUrl from outside
- creating a basic k8s configuration

**Comment by Paulomart** [comment]
Time spent: 2 hours 30 minutes

* #186 
* Prepare repo for infrastructure: https://github.com/Oeffis/infrastructure

**Comment by timvahlbrock** [comment]
Time spent: 2 hours 30 minutes

* #186 
* Prepare repo for infrastructure: https://github.com/Oeffis/infrastructure
