### ISSUE TITLE
Route Planning: Add user input to switch between departure and arrival

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#294]
Route Planning UI is missing some input to switch between using given date/time as departure or arrival for the journey to be planned.  Backend is already providing this function, but Frontend is passing `false` to _asArrival_ property statically (in requests).

There could be some sort of slider or a checkbox to switch between interpreting given date/time as departure or arrival (or some other similar input element).
```[tasklist]
### Tasks
- [x] Implement functionality for arrival/departure toggle button
```

**Comment by AconexOfficial** [comment]
Already implemented in:
[Style Route Planner#373](https://github.com/Oeffis/Oeffis/issues/373)
[Connect departure/arrival toggle with backend#452](https://github.com/Oeffis/Oeffis/issues/452)
