### ISSUE TITLE
Create journey start page

### ISSUE THREAD

**Issue by dkrakau** [Oeffis/Oeffis#295]

**Comment by timvahlbrock** [comment]
Time spent: 5 hours

Spent on pair programming on:
+ fcda52fa997ec6fea4eafad76de843e033104453 Fix imports for LoactionSearchInput component
+ d14b7e88a486a5a6d56b5fe2fe9a89d95d31a3c1 Extract CurrentMapMarker from MapMarker component
+ c0b7ade5a370e242973c345b7e18236f4424f1d8 Change locations type from Location-Array to String-Array
+ dd767ad33cd3fdfe6b742b8ab75840eec6ca94fa Add currentLocation prop to destination LocationSearchInput
+ d4afdea014fb50ff9245d9717dbc7d8d5b7b17cd Remove currentLocation from locations elements
+ a6d3e4038aaa98417dc4c008dbedc14ea558758d Add getLocationCoords to LeafletMapContainer
+ e6c1275e1a4db2bf8136a2f64af397dd42c5b736 Create useMultipleLocations Hook
+ 6b4aab20bb128c2411596a80e0b1910d5fc3fcd3 Remove CurrentLocationId from locations array
+ 6d890778db9039df7f568f9085cbb82d50877644 Implement useMultipleLocations Hook in Map Container
+ d31e3c4f3b6660902c46b4013de21ad8317c1596 Change key prop locations to locationIds
+ 634bbd5e47431d138131f435ff36e8622f34e1d7 Remove flyToBounds from MapController
+ 83ede9f7b8033837bdcddbe8a9f36e96388d7301 Remove MapController from Map
+ 8707944af23ec5b6f9d9034bf7144e237ee377e3 Remove getBounds from MapContainer

**Comment by dkrakau** [comment]
Time spent: 37 hours

Spend on:

+ 2c80f6fbcb42d2a568f758dc05ff8c305466cfe3 Create journey start page
+ 55fd266a087b8126e3eb79dd0e315b243373d304 Implement map selection for origin and destination
+ da6f09b339e86e33e5fb7760421ac60126738ac7 Fix es lint error
+ 50f0f19008bdb0cb34999219c9e15aa61e8bea9e Fix es lint error
+ 1d0318305f5ed570ca6113ee68a06161461fccf1 Add location selection on map
+ 15d7bf8f9ad1a3a99ed193aec8282b4d4b170228 Remove test function
+ 2787f2e00d08b6deb41689574f26fbae17586fa5 Fix map button function
+ d98202f81cc8141a22e8777c84d2dffe14977577 Add geolocation dependency
+ 730f50ad059f4d2895e7fa9780aa764dea9af36a Add buttons to side menu
+ 4eb2112fcfc9efcf0fe0738350150950142c03d7 Create map controller component
+ c2242a54c5736f27eb437126ac8b347403af208c Add lines and markers to map
+ ce9afbf435aa08be33d6bcaee6ac3a2325d5f62f Integrate map into routeplanner modal
+ 36773c8efff08f1e70a95b7997eccb0ef8ac25ee Integrate map and routeplanner into journeypage
+ 7f9275164bb38740658cad4a8213f12ab78d3b70 Add green map marker
+ 8fb8db4272fe9d97334045ae7722641058d8cc97 Add red map marker
+ 4989d9bf5a23922c1e8d0afa72fa47e250a9370d Add white map marker
+ b9a439790265b3dcfd2c2d04a1718ae1bd7781b6 Add current postion icon and shadow image for map marker
+ 32bc2f33bb6054750df9450f8a7eb5bfcb244ffd Create MapMarker component
+ 99c90ad40682f8c50b579898ff0b2b83826445be Add current location to found locations
+ 7e5223cccd61beee1391e91bc87c01d32b07e268 Rename css tags and select button
+ fb9e45cbcb569f0fe0aecb7ebc3573ca3b32e9b5 Add origin/destination to map container and use MapMarker component
+ 8000e10a522de5212be9b62e0e28859e63d0778f Remove merge conflicts
+ c15ddf48d4a575e77e486caf4b3132cbf36cd298 Move images from public to src folder
+ 26432ee02337286e1ec20146e37a9e2e1250d665 Add key attribute to journeyDetail component
+ c0338572ac451eb7e3e80320230afbc5455b0483 Move map components to map folder
+ faa8d078dfc77b5482e6fc4677b9d4427ac256cf Fix eslint error
+ da66c03488a69727611333e9e5c182fef276cea9 import runtime to use exists function
+ e518911646dd62f18d6fe1507f6c38acd171678c Remove RoutePlanner component from Home page
+ 867bf260f8363549a6c34f0c651382ce9a1626e6 Edit comment for issue with current time
+ fa027aaaf2320cc893ec6eecff0565c8c200c3cc Switch Start/Ziel label in MapMarker
+ 1536506bf9b2c2fc43779b84eb547e147d0497ae Add unique key for JourneyStepCompnent in JourneyDetail component
+ 52cc6e5575670502608db8322f9a89a1c612fa60 Switch export to export default for MapController
+ 270e61553d815dfaaa9cbcee7ac0b7c43a4326e1 Fix e2e test ids
+ 988430356e97739ee4bc195c9c9bfce8f25b58f1 Add buttons to menu
+ 16959170908254f61640dfb7faae8980f9989717 Add routes to App component
+ a7fad9dd8cae830dddf9775fba763d8864e51ac6 Create UserHistoryPage
+ 5bce2f06436e5c87ca602e46577ca088585a62a9 Create UserPreferencesPage
+ 5e5dfd302c3ca5824046738abf6612d4e90d251e Remove Menu component from JourneyPage
+ 4091b0d8e5e5d9304340ad20d0ad96fc3c82b12f Add keys to FavoriteTripsComponent
+ 7935142d012e62bf2938332714960726bc4697bf Add dependency for Swiper
+ ec938fc9c30ba6c3f777343b45345292f844f4ff Create FavoritesPage with implemented Swiper
+ a586803fa8ec91248ba73f63eeeaca4a8ddbc39f Fix eslint error
+ fa0c241b73d691f4d19aa48833190d46bb65110c Remove swiper-wrapper class from FavoritesPage CSS file
+ a2a8df4460d948b74a6ea5bc552bf27d0ce649c5 Fix eslint error
+ aeb0e3d92529223a3a4824d561828a562523d47a Fix e2e error
+ 208d2d52fee03c6a6363cece8663907dfde54679 Fix e2e error
+ f1f52fe916e8aa51ab78178046e235991a83446e Fix e2e error
+ fcda52fa997ec6fea4eafad76de843e033104453 Fix imports for LoactionSearchInput component
+ d14b7e88a486a5a6d56b5fe2fe9a89d95d31a3c1 Extract CurrentMapMarker from MapMarker component
+ c0b7ade5a370e242973c345b7e18236f4424f1d8 Change locations type from Location-Array to String-Array
+ dd767ad33cd3fdfe6b742b8ab75840eec6ca94fa Add currentLocation prop to destination LocationSearchInput
+ d4afdea014fb50ff9245d9717dbc7d8d5b7b17cd Remove currentLocation from locations elements
+ a6d3e4038aaa98417dc4c008dbedc14ea558758d Add getLocationCoords to LeafletMapContainer
+ e6c1275e1a4db2bf8136a2f64af397dd42c5b736 Create useMultipleLocations Hook
+ 6b4aab20bb128c2411596a80e0b1910d5fc3fcd3 Remove CurrentLocationId from locations array
+ 6d890778db9039df7f568f9085cbb82d50877644 Implement useMultipleLocations Hook in Map Container
+ d31e3c4f3b6660902c46b4013de21ad8317c1596 Change key prop locations to locationIds
+ 634bbd5e47431d138131f435ff36e8622f34e1d7 Remove flyToBounds from MapController
+ 83ede9f7b8033837bdcddbe8a9f36e96388d7301 Remove MapController from Map
+ 8707944af23ec5b6f9d9034bf7144e237ee377e3 Remove getBounds from MapContainer
