### ISSUE TITLE
Meeting to discuss Live Navigation

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#299]
- [x] Discuss handling menu interaction (Favourites, Options, etc.) while using live navigation.
- [x] Wireframes
- [x] Favourites
- [x] Create issues

**Comment by AconexOfficial** [comment]
Time spent: 2 hours

**Comment by Escowei98** [comment]
Time spent: 2 hours

**Comment by LaraBiss** [comment]
Time spent: 2 hours

**Comment by dkrakau** [comment]
Time spent: 2 hours
