### ISSUE TITLE
Add postgresql via docker-compose

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#309]
- [x] Add docker-compose.ymal
- [x] Add automatic import of schmea

**Comment by timvahlbrock** [comment]
Time spent: 30 minutes

Spent on:
+ 9a971a31193264b764ae81958879632fd34fa095 add compose file and idea configuration for postgres db

**Comment by timvahlbrock** [comment]
Time spent: 30 minutes

Spent on:
+ d14e69312f5aeeceba21d55b88acd4b0c8b0d173 add support for schema init
