### ISSUE TITLE
Choose License

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#31]
- [x] Discussion
- [x] Add LICENSE file to repo
- [x] Add license notice to package.json
  - [x] frontend
  - [x] backend
- [ ] make sure GitHub Repo info is updated

**Comment by timvahlbrock** [comment]
Hey @Oeffis/core-team I took a look around GitHub's [choosealicense.com](https://choosealicense.com) and would like to propose the [AGPLv3](https://choosealicense.com/licenses/agpl-3.0/) license. Just like GPLv3, it enforces that other software using this one also disclose their source code, but with the benefit that "Network use is also distribution" - so if the software is provided as a service any additional code will need to be disclosed as well. Can I get a quick 👍 👎  voting on this, till this afternoon?

**Comment by timvahlbrock** [comment]
Last point needs to be checked when #43 is merged

**Comment by timvahlbrock** [comment]
Time spent so far: 1h

**Comment by timvahlbrock** [comment]
Time spent: 1h
