### ISSUE TITLE
2023 09 15: Historic Data Aggregation (Meeting)

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#311]
Design a system to gather data from vrr about historic delays.

**Comment by Paulomart** [comment]
Time spent: 2 hours

**Comment by timvahlbrock** [comment]
Time spent: 2 hours

**Comment by JaJako** [comment]
Time spent: 30 minutes

Looking into results of meeting and current state of implementation.

**Comment by timvahlbrock** [comment]
Time spent: 2 hours
