### ISSUE TITLE
Lack of type safety on internal API

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#319]
The issue #318 could have been caught before, if we had enforced strict type checking on our internal API. Currently, all API fields are optional, but the frontend assumes them to be present. We should fix this ASAP, in my opinion making only API fields optional that actually are optional non should be the correct way to go. In most cases we should get around undefined or null fields by properly using type polymorphism and safe defaults.

- [x] Fix optional fields are being interpreted as required during api generation.
- [x] Is some further validation/transformation needed for Backend?
- [x] Adjust UI to resolve type conflicts ("... can be undefined").
- [ ] #321

**Comment by timvahlbrock** [comment]
Time spent: 30 minutes

Spent on:
- debugging
- documenting
- planning

**Comment by Paulomart** [comment]
The backend generated schema includeds required tags:

https://github.com/Oeffis/Oeffis/blob/e77fe9c52c88d17f3fd5347f8ccd6b4cb7a92298/backend/swagger-spec.json#L447-L450

So when generating the frontend code the api things they are non optional, while the backend code will allow them to be optional.

**Comment by Paulomart** [comment]
I think we need to implement this: https://stackoverflow.com/questions/64483978/validate-response-format-in-nestjs

**Comment by JaJako** [comment]
> Instead of explicitly typing the @ApiProperty({ required: false }) you can use the @ApiPropertyOptional() short-hand decorator. (https://docs.nestjs.com/openapi/types-and-parameters)

If not stated, required: true seems to be the default, indeed. Will try the `@ApiPropertyOptional()`.

**Comment by JaJako** [comment]
Time spent: 2 hours

Fixing optional fields not generated into frontend client + enabling validation in Backend.

**Comment by JaJako** [comment]
Time spent: 1 hour

Fixing Frontend code temporarily (until #321).
