### ISSUE TITLE
Adapt Project Board to agreed Workprocess

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#32]
The work process has been laid out in #4. The project needs to be aligned properly.

- [x] align board states
- [x] state transitions happen automated, where possible (workflows)
- [ ] issues have required fields

**Comment by JaJako** [comment]
@timvahlbrock I will take a look at that.

**Comment by Paulomart** [comment]
Time spent: 2 hours

**Comment by timvahlbrock** [comment]
@JaJako needs to add the time he spent on this issue.

**Comment by JaJako** [comment]
Time spent: 2 hours

**Comment by JaJako** [comment]
Time spent: 2 hours

**Comment by JaJako** [comment]
Time spent: 2 hours

**Comment by JaJako** [comment]
Time spent: 2 hours
