### ISSUE TITLE
Rework backend types (optional fields, used types, missing fields, wrapping)

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#321]
As a second step to #319 (doing the urgent fixes) this issue is designed to rework (some of) the backend types. It should be checked, which fields really has to be optional (and which dont). Fields that should not be optional, has to get some default values (or some similar treatment) when dealing with some undefined/null value during processing. If some indispensable value is missing that cannot be replaced by some simple default, an error should be thrown (normally vrr api should not return such data). 

Also while checking all entities/dtos I found some used types that do not match fully or fields that never have a value. As the first approach to introduce these types just captured the needs and knowledge back then, there are some more fields that should be part of our custom types. One big group of missing fields is about foot navigation. This is a complex structure of types itself and therefore won´t be handled in this issue but in an own issue, see #338.

- [x] Rework types for location (use of optional, used types, missing fields).
- [x] Adjust wrapping of location types
- [x] Rework types for journey (use of optional, used types, missing fields).
- [x] Adjust wrapping of journey types
- [x] Re-Generate and adjust Frontend

**Comment by JaJako** [comment]
Time spent: 1 hour 30 minutes

Documenting why custom types are designed as they are (including some example structures).

**Comment by JaJako** [comment]
Time spent: 2 hours

Finishing up implementation for location entities/dtos.

**Comment by JaJako** [comment]
Time spent: 1 hour

Adding tests for location mapping.

**Comment by JaJako** [comment]
Time spent: 1 hour 30 minutes

Analyzing VRR journey structures.

**Comment by JaJako** [comment]
Increased planned hours after reworking location types (first part of issues) to new estimation (based on work process and needed time so far).

**Comment by JaJako** [comment]
Time spent: 3 hours 30 minutes

Finishing up analyzing VRR Journey structures (specifically looking into fields about footpaths/navigation).

**Comment by JaJako** [comment]
Time spent: 4 hours 30 minutes

Reworking journey entities/dtos.

**Comment by JaJako** [comment]
Time spent: 2 hours 30 minutes

Adjusting implementation of mapper + adding unit tests.

**Comment by JaJako** [comment]
Time spent: 1 hour

Further implementation of mapper + unit tests.

**Comment by JaJako** [comment]
Time spent: 3 hours

Implementing missing mappers + unit tests.

**Comment by JaJako** [comment]
Time spent: 4 hours

Improving + further implementing tests and leg details mapper.

**Comment by JaJako** [comment]
Time spent: 1 hour 30 minutes

Implementing Mapper for minimal Footpath entity + unit tests.

**Comment by JaJako** [comment]
Time spent: 2 hours

Introduces separate location coordinates mapper + starting to implement journey location mapper.

**Comment by JaJako** [comment]
Time spent: 1 hour 30 minutes

Finishing up type adjustments in Frontend.

**Comment by JaJako** [comment]
Time spent: 2 hours

Fixing test + rebasing and finishing up issue (open PR).

**Comment by JaJako** [comment]
Time spent: 30 minutes

Fixing broken test.

**Comment by Paulomart** [comment]
Time spent: 2 hours

Review.

**Comment by JaJako** [comment]
Time spent: 2 hours

Applying feedback from review/PR.

**Comment by timvahlbrock** [comment]
Time spent: 2 hours

Spent on:
- Review
