### ISSUE TITLE
Create Wiki Entry for Wireframes

### ISSUE THREAD

**Issue by LaraBiss** [Oeffis/Oeffis#323]
- [x] add route planner wireframes to wiki
- [x] add route planner description
- [x] add live navigation wireframes to wiki
- [x] add live navigation description
- [x] add favorite wireframes
- [x] add burger menu wireframe
- [x] add description to burger menu and favorite

**Comment by LaraBiss** [comment]
Time spent: 2 hours 30 minutes

Spent on: create entries for route planning and live navigation, write description in german

**Comment by LaraBiss** [comment]
Time spent: 30 minutes

Spent on: update route planner description and translate, update images

**Comment by LaraBiss** [comment]
Time spent: 2 hours

Spent on: 
translate description of route planner wireframe wiki entries 
update description
include information from discussion of wireframes
update layout

**Comment by LaraBiss** [comment]
Time spent: 1 hour

Spend on: 
adding favorite wireframes
update live navigation wireframes
adding description to live navigation wireframes

**Comment by LaraBiss** [comment]
Time spent: 1 hour

Adjust wireframes, tidy up

**Comment by LaraBiss** [comment]
Time spent: 2 hours 30 minutes

Spend on: 
adjusting wireframes
change wireframe language to german
update wireframes in wiki for route planner & live navigation & favorites
update description in wiki for route planner & live navigation 
write description in wiki for favorites

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 30 minutes

Spend on: discussion and adjustment of favorites wireframes
