### ISSUE TITLE
Start/End navigation

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#328]
- [ ]  Create start navigation button
- [ ] Start navigation process
- [ ] Create end navigation button
- [ ] Stop navigation process

**Comment by Escowei98** [comment]
Time spent: 6 hours

**Comment by Escowei98** [comment]
Time spent: 2 hours

**Comment by LaraBiss** [comment]
Time spent: 30 minutes

Spend on: review
