### ISSUE TITLE
Layout apps basic design

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#33]
- [x] Find suitable wireframe method
- [x] Create a wireframe mockup for pc browser (basic functions)
- [x] Create a wireframe mockup for mobile browser (basic functions)
<del>- [ ] Design an App Icon</del>
- [x] Create a discussion for everyone to participate
- [x] Adjust wireframe mockup to the feedback

**Comment by Paulomart** [comment]
@AconexOfficial Why is this issue in Done, but not closed?

**Comment by AconexOfficial** [comment]
Time spent: 8.5 hours

**Comment by AconexOfficial** [comment]
Discussion link: [#54](https://github.com/Oeffis/Oeffis/discussions/54)

**Comment by AconexOfficial** [comment]
Figma link of the web browser: 
[Wireframe: Web browser](https://www.figma.com/file/y1MLDz9KPjwKa6MqFeEdIp/Prototyp?type=design&node-id=0%3A1&t=JKm7Xb5xhiMlm6zH-1)

**Comment by LaraBiss** [comment]
Time spent: 8 hours 30 minutes

**Comment by LaraBiss** [comment]
Link for mobile version [click](https://www.figma.com/file/O7dJ1NyevhYLitnOwRnI6M/Mobile-Prototyp?type=design&t=kHOu55mkR15ct2Nf-1)
