### ISSUE TITLE
App styling

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#34]
- [x] color examples
- [x] color poll
- [x] specific colors
- [x] Fonts
- ~~[ ] Spacing/Formatting~~ in #204 
- ~~[ ] Shapes~~ in #204 
- [x] Icon Style
- ~~[ ] Animation Types~~
- ~~[ ] Interaction Feedback~~
- [x] Create wiki entry with results

**Comment by LaraBiss** [comment]
Time spent: 9 hours

Spend on: 
- how to style guide (best practice, what to include)
- search for a tool (there are no good tools -> using figma / wiki entry)
- color scheme examples (figma + Ionic personal theme generator)
- font and icons

**Comment by LaraBiss** [comment]
Time spent: 2 hours

Spent on:

- bicolored examples

**Comment by LaraBiss** [comment]
Time spent: 2 hours 30 minutes

Spent on:
- create colorable Icons
- updated color examples
- create color scheme poll

**Comment by LaraBiss** [comment]
Time spend: 4 hours

Spend on:

- Structure Style Guide
- choose icons

**Comment by LaraBiss** [comment]
Time spent: 3 hours

Spend on: 
- create wiki entry

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

Review
