### ISSUE TITLE
Rework Journey Step Component (add attributes, adjust design)

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#340]
- [x] Rework design to Wireframes
- [x] Add attribute to pass progress from step to step
- [x] Add line to IJourney interface
- [x] Live-Updates for Progress bar

**Comment by Escowei98** [comment]
time spent: 3 hours

**Comment by Escowei98** [comment]
time spent: 3 hours 30 minutes

**Comment by JaJako** [comment]
As I just stumpled over some ambiguities with journey steps, some input, if that's not covered with this issue already (I think some of them are solved in the wireframes already):


![Image](https://github.com/Oeffis/Oeffis/assets/53478084/ed152733-ce5d-4478-81af-6b413ae1d4cc)


- Departure time and arrival time are labled wrong (switched)
  - Should be enough to list times in the left column anyway
- **In my opinion it would be natural to show departure time only on start, arrival time only on end and departure+arrival times both on intermediate stops (in left column)**
- information about current location and next stop/destination in journey is quite confusing in current state (example: "Essen Altenessen Hbf'Gelsenkirchen Hbf'")
- missing information like transportation type / name etc. (but that's obviously part of this issue already, as I understand the title)
- **calculated time of journey (on the right in journey header) does not matches with difference of arrival on end and departure at start**

Like I´ve said just some ideas, that maybe are considered already.

**Comment by Escowei98** [comment]
time spent: 4 hours 30 minutes
