### ISSUE TITLE
Deploy Delay Crawler

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#343]
- [x] Adjust crawler to be configable via env
- [x] Create k8s deployment

**Comment by Paulomart** [comment]
Time spent: 12 hours

* Debugging issues with postgres and node
* Deployment of the crawler
* Adjustments to crawler code

**Comment by Paulomart** [comment]
@timvahlbrock  the crawler encounted an error:

```
Fetching stop id from DB...
stop is a station, using station id instead
fetching delays for stop id de:05113:9224
Ignoring error while parsing response Error: Invalid value for key "stopEvents" on DMTTPSchema. Expected an optional object but got (...)
    at invalidValue (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:386:11)
    at transformUnion (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:435:16)
    at transform (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:491:53)
    at /app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:465:32
    at Array.forEach (<anonymous>)
    at transformObject (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:462:43)
    at transform (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:493:49)
    at cast (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:501:12)
    at toDMTTPSchema (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:375:16)
    at /app/node_modules/@oeffis/vrr_client/dist/VrrClientBase.js:9:20
inserted 100 departure events into DB, 0 failed
```
[crawlererror.txt](https://github.com/Oeffis/Oeffis/files/12859576/crawlererror.txt)

**Comment by timvahlbrock** [comment]
> @timvahlbrock the crawler encounted an error:
> 
> ```
> Fetching stop id from DB...
> stop is a station, using station id instead
> fetching delays for stop id de:05113:9224
> Ignoring error while parsing response Error: Invalid value for key "stopEvents" on DMTTPSchema. Expected an optional object but got (...)
>     at invalidValue (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:386:11)
>     at transformUnion (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:435:16)
>     at transform (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:491:53)
>     at /app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:465:32
>     at Array.forEach (<anonymous>)
>     at transformObject (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:462:43)
>     at transform (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:493:49)
>     at cast (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:501:12)
>     at toDMTTPSchema (/app/node_modules/@oeffis/vrr_client/dist/vendor/VrrApiTypes.js:375:16)
>     at /app/node_modules/@oeffis/vrr_client/dist/VrrClientBase.js:9:20
> inserted 100 departure events into DB, 0 failed
> ```
> 
> [crawlererror.txt](https://github.com/Oeffis/Oeffis/files/12859576/crawlererror.txt)

Yes, but this is a warning from you schema parser. The stops are inserted nevertheless.
