### ISSUE TITLE
Adjust Wireframe details

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#344]
- [x] Localize wireframes for german language
- [x] Edit details of Route Planner wireframes
- [x] Edit Live Navigation notification wireframes
- [x] Edit Route Details informations wireframes
- [x] Adjust input modal wireframes
- [x] Standardize font sizes
- [x] discuss how to display time and date for arrival and departure
- [x] coding position in live navigation with something else then just color?
- [x] adjust burger menu: route planner and live navigation option? which settings do we have?

**Comment by LaraBiss** [comment]
Time spent: 2 hours 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by LaraBiss** [comment]
Time spent: 1 hour
