### ISSUE TITLE
Analyse current vrr data and understand structure

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#347]
- [x] Figure out why all times are "special"
- [ ] Connect historic_data to vrr provided data (timetables)

**Comment by Paulomart** [comment]
Time spent: 8 hours

* Further research into data. 
* Currently Iam unable to deduce four of the unknown fields. See #357

**Comment by Paulomart** [comment]
Maybe someone elese can take a look at this?

**Comment by JaJako** [comment]
Time spent: 30 minutes

Looking into current findings (notebook).

**Comment by JaJako** [comment]
Time spent: 30 minutes

Looking into final data / separation of trip_id fields/elements.

**Comment by Paulomart** [comment]
Time spent: 30 minutes
