### ISSUE TITLE
Create presentation for 24.10

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#351]

**Comment by timvahlbrock** [comment]
Time spent: 1,5 hours

**Comment by timvahlbrock** [comment]
Time spent: 1 hour 30 minutes

**Comment by JaJako** [comment]
Time spent: 1 hour

Preparing presentation (some general part and personal part).

**Comment by JaJako** [comment]
Time spent: 1 hour

Further preparation of personal part in presentation.

**Comment by LaraBiss** [comment]
Time spent: 2 hours

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by dkrakau** [comment]
Time spent: 1 hour 30 minutes

**Comment by Escowei98** [comment]
Time spent: 1 hour 30 minutes
