### ISSUE TITLE
Add e2e tests for existing features

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#356]

**Comment by timvahlbrock** [comment]
Time spent: 4 hours

Spent on:
+ 15a309a8b664899c037b8ec7b63db1230a35e629 Fix wrong collection being selected ate end of e2e tests
+ d51fdda9be2c98cb268c9f927d7bdaabd74bfcc4 Fix collection extending default
+ 41159fc904afabd9424af96fb5c364cc0e1b157e fix e2e tests
+ 2e2c988175ddf01c8bf6dbaf9a6d0aa22990fd92 Improve wording for setting a collection
+ 0bde3227159c22c664b825866dbc7bf501e3b993 add e2e test for route selection

**Comment by JaJako** [comment]
Time spent: 30 minutes

Reviewing fix to locations in stop sequence without planned times.

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

Spent on:
+ a7f4b24da5fe77b4e98d61ee4575edf3d4972702 add berlin time zone
+ 950d33e49ea1441b764190525df7c3122f9d8a15 fix tz var position
+ 52c7238923fb626e3a65415f9da1df081f97df7d Make departureTime and arrivalTime optional
+ 4afa7a9c88e4685fc7440600df893bf859c162c1 make times optinal in constructor
+ c99d93352ddc810dc3ce1ac1acfe27255a5246f8 Update frontend types
+ fed22615d4b5bd00427e8100e815624b12908fbc filter out unneeded locations, fix tests
+ 90fdedc242ce687ef8cba53fb411766aa3435ee4 Address requested changes

**Comment by timvahlbrock** [comment]
Time spent: 30 minutes

Spent on:
+ abd849b1521b69d25173bf18289c0d0c22bdbdaa remove outdated test
+ ddb034c206d14d62c4ddbd2505909b5d8a3c9794 fix linting error
