### ISSUE TITLE
Consider school holidays and on-request schedules

### ISSUE THREAD

**Issue by kayman-mk** [Oeffis/Oeffis#358]
**Describe the bug**
It seems that the time tables are not imported completely. Just discovered on CeBus 260 from Neu Lutterloh to Unterlüß Bahnhof (Lower Saxony, Germany) on saturdays, that the 19:08 connection is only valid on school days (not during holiday) and on-request only (you have to dial the bus company at least 59 minutes before departure).

**To Reproduce**
Fetch the schedule mentioned above in the app.

**Expected behavior**
Do not propose the connection as the schools are closed at the moment. In case of a school day, show a note that the bus company has to be dialed before.

**Comment by kayman-mk** [comment]
Current time table: https://www.cebus-celle.de/fileadmin/user/pdf/fahrplaene/260_.pdf

Seems to be different from the one published at the bus stop. There is no indication in the PDF above that 19:08 on saturdays is valid on school days only.

**Comment by timvahlbrock** [comment]
Closing this for now. Feel free to reopen if this is actually the repo you were looking for.

**Comment by kayman-mk** [comment]
Oh yes, you are right. The project I was looking for is hosted on GitLab. https://gitlab.com/oeffi/oeffi
