### ISSUE TITLE
Tidy Wiki

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#36]
- [x] Move each meeting to own file
<del>- [ ] Reference meeting files from closed discussion, issues</del>
- [x] Fix broken layout
- [x] Create categories and a suitable hierarchy
- [x] Create front page with overview

**Comment by AconexOfficial** [comment]
Time spent: 2 hours 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 2 hours 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 2 hours 30 minutes
