### ISSUE TITLE
Style Route Planner

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#373]
- [x] Align page name
~~- [ ] Fix Calendar year selection~~
~~- [ ] Check infinite scroll though date and time selection~~
- [x] Fix Date and Time label is cut off
- [x] Create new Date and Time component
- [x] Add Date and Time icon
- [x] Add toggle arrival/departure time
- [x] Adjust "Search Routes" Button
- [x] Adjust "Add to favorites" Button
- [x] Remove "Show favorites" Button
- [x] Add "X" delete option for input fields
- [x] Add icon button to switch origin and destination 
- [x] Adjust sizing
- [x] Adjust proportions of Route Planner and Map to accommodate changes
- [x] Change language of displayed texts to german
- [x] Create CSS-Modules
- [x] Clean up previous RoutePlanner.css

**Comment by AconexOfficial** [comment]
Time spent: 4 hours

**Comment by AconexOfficial** [comment]
Time spent: 1 hour 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 3 hours 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

Rewriting CSS for route planner to use css modules

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

Looking into merge conflict

**Comment by AconexOfficial** [comment]
Time spent: 2 hours

Resolved merge conflicts
Small adjustments to spacing
