### ISSUE TITLE
Style Modal

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#374]
- [x] Remove Map button from top
- [x] Add Map button as floating action button
- [x] Add List button as floating action button when in map mode
- [x] Change Favorite icons
- [x] Adjust cancel button
- [x] Adjust pop-up when selecting a location on map
- [x] Refactoring CSS for Buttons
- [x] Translate Modal in German

**Comment by LaraBiss** [comment]
Time spent: 5 hours 30 minutes

Spend on: adjustments in styling and started refactoring

**Comment by LaraBiss** [comment]
Time spent: 3 hours 30 minutes

Spend on: 
- change language
- adding component for floating action button
- change map / list button in modal to floating action button

**Comment by LaraBiss** [comment]
Time spent: 1 hour

Spend on: Troubleshooting

**Comment by LaraBiss** [comment]
Time spend: 3 hours

Spend on: Adjust map popup

**Comment by LaraBiss** [comment]
Time spent: 3 hours

Spend on: Adjust map popup
