### ISSUE TITLE
Style Route Options

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#375]
~~- [ ] Remove date from result~~
~~- [ ] Show train names instead of station names~~ Handled in separate issue
~~- [ ] Make showing more than 4 train connections have a ... in the middle~~ Handled in separate issue
- [x] Adjust minutes/hours
- [x] Add footer to return to route planner
~~- [ ] Show currently selected card~~
- [x] Fix header
- [x] Refactor css into module.css
- [x] Adjust correct sizing/padding/margin

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 1 hour 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

Working on getting lines of all necessary legs

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by AconexOfficial** [comment]
Time spent: 2 hours

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

Create module.css, adjust margin and fix header

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

Merge conflicts

**Comment by AconexOfficial** [comment]
Time spent: 1 hour 30 minutes

Fixed sizing and padding

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

Resolving merge conflicts

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by LaraBiss** [comment]
Time spent: 30 minutes
Spend on: review

**Comment by AconexOfficial** [comment]
Time spent: 1 hour 30 minutes
