### ISSUE TITLE
Style Route Details

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#377]
~~- [ ] Add "Start Navigation" button~~
- [x] Make route top and details differentiate visually (header & body color)
- [x] change route details from flex to grid
~~- [ ] Remove dates from details~~
~~- [ ] Show train name instead of stations~~
~~- [ ] Show total travel time of train instead of departure and arrival~~
- [x] Show platform
~~- [ ] Add adjustments for footpath~~
~~- [ ] Calculate available time for foottravel~~
- [x] Add favourite floating action button
~~- [ ] Add Icon for vehicle~~
- [x] Add Label "Ankunft"
- [x] Add color 
- [x] Adjust font size
- [x] Adjust radio button
- [x] discuss display delay stats
- [x] make header a component and reuse in route details

**Comment by LaraBiss** [comment]
Time spent: 18 hours

Spend on: 
- update tasklist
- read up on css grid
- update components
- implement css grid
- adjust layout
- adjust styling
- fix radio buttons
- fix styling
- update css classes

**Comment by LaraBiss** [comment]
Time spent: 4 hours

Spend on: 
- adjust layout
- favorite button

**Comment by LaraBiss** [comment]
Time spent: 2 hours 30 minutes

Spend on:
- solve merge conflicts
- fix live navigation button

**Comment by LaraBiss** [comment]
Time spent: 3 hours 30 minutes

Spend on:
- Update tasklist
- favorite
- show plattform
- display delay stats
- css

**Comment by LaraBiss** [comment]
Time spend: 2 hour 30 minutes

Spend on: 
- searching for favorite trip/route implementation
- fix layout for display delay stats and track
- some adjustments at grid
- solve merge conflicts

**Comment by LaraBiss** [comment]
Time spent: 2 hour 30 minutes

Spend on:

searching for favorite trip/route implementation
fix layout for display delay stats and track
some adjustments at grid
solve merge conflicts

**Comment by LaraBiss** [comment]
Time spent: 4 hours 30 minutes

Spend on: 

- solve merge conflicts
- understanding favorite implementation
- add trip to favorites
- try to remove trip from favorites (but was not yet implemented)
- reproduce bugs in favorites to discuss later
- make list of bugs in favorites

**Comment by LaraBiss** [comment]
Time spend: 7 hours 30 minutes

Spend on: 
- merge conflicts
- discuss favorites and route detail implementations 
- delete favorite button
- create missing css modules for components
- tidy up css classes
- delete not used css

**Comment by LaraBiss** [comment]
Time spent: 7 hours 30 minutes

Spend on:

- merge conflicts
- discuss favorites and route detail implementations
- delete favorite button
- create missing css modules for components
- tidy up css classes
- delete not used css

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes
