### ISSUE TITLE
DBO schemas for current database layout

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#380]
* Create objects/class for use of the database types in backend

**Comment by JaJako** [comment]
@Paulomart @timvahlbrock To get it right, what's the task here: Creating classes/"entities" like this one for example: https://docs.nestjs.com/recipes/sql-typeorm#repository-pattern (obviously depending on using typeorm in this example, which is furthermore looking very suitable for what we want to do). But means before we have chosen how to add database to backend, there is no meaning in starting to define any types here (apart from versioning topic), right?

**Comment by Paulomart** [comment]
> To get it right, what's the task here: Creating classes/"entities" like this one for example: https://docs.nestjs.com/recipes/sql-typeorm#repository-pattern

yes.

> But means before we have chosen how to add database to backend, there is no meaning in starting to define any types here (apart from versioning topic), right?

IMO you can investigate multiple options and implement your choice then.

**Comment by timvahlbrock** [comment]
I will try to implement database connection later today

**Comment by JaJako** [comment]
Time spent: 4 hours 30 minutes

Setting up entities + relationships (DBO Schema).

**Comment by JaJako** [comment]
Time spent: 1 hour

Re-checking and fixing type/entity definitions.

**Comment by JaJako** [comment]
Time spent: 30 minutes

Adding UNIQUE constraints + doing first short test.

**Comment by JaJako** [comment]
Time spent: 3 hours

Fixing name schema + relation definitions; activate first entities.

**Comment by Paulomart** [comment]
Time spent: 1 hour 30 minutes

**Comment by JaJako** [comment]
Time spent: 4 hours 30 minutes

Fixes definitions+relations to support objects + problems with stop parents.

**Comment by JaJako** [comment]
Time spent: 3 hours 30 minutes

Fixing relationships of entities + finishing up work.

**Comment by JaJako** [comment]
Time spent: 30 minutes

Rebasing onto main (adding tripCode field to DelayEntry).
