### ISSUE TITLE
Favorite view: Not closable on mobile

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#386]
**Problem**
Using 'Show Favourites' on a mobile device with small screen size the favourite view cannot be closed (on Desktop you can press escape, but there's no mobile/touch equivalent yet).

**Solution**
There should be some button to close favourites' view.

**Comment by JaJako** [comment]
<img src="[drawing.jpg](https://github.com/Oeffis/Oeffis/assets/53478084/231c2a5c-f5af-4c8f-8c8d-4b317c91fa9e)" alt="drawing" width="200"/>

**Comment by AconexOfficial** [comment]
Time spent: 2 hours

**Comment by LaraBiss** [comment]
Time spent: 30 minutes
Spend on: review
