### ISSUE TITLE
Favourites view: Swiping between views inconsistent/not obvious

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#389]
~~- [ ] representation of current swipable page on iPhone not ideal (see screenshot)~~ **seems to already have been resolved**
~~- [ ] clicking on one 'page representation element' page is not changed while representation element is (see screenshot) => clicking elements manually should change page, too or these inputs should be disabled/non-clickable.~~ **seems to already have been resolved**
- [x] option to change page via swiping is not obvious (especially with iPhone representation). Maybe adding some left and right arrow next to current page representation to indicate option of swiping + good way to have ability of "swiping manually" by clicking that arrow (better than clicking representation elements which leads to inconsist states currently).

**Comment by JaJako** [comment]
That's how it is looking on iPhone. 

<img src="[drawing.jpg](https://github.com/Oeffis/Oeffis/assets/53478084/9843e5a3-795d-4c0a-88f4-de6b863f4434)" alt="drawing" width="200"/>

**Comment by JaJako** [comment]
Clicking on checkbox (representing selected page) manually changes checkbox state but not shown page (inconsistency):


<img src="https://github.com/Oeffis/Oeffis/assets/53478084/d8d0cb3f-3aea-43fb-8a0a-2fa6a4a346f6" alt="drawing" width="200"/>

**Comment by JaJako** [comment]
What about something like this. Arrows suggest you can swipe between pages + clicking arrows changes page, too (good for non-touch devices). Checkboxes can be disabled/non-clickable then to avoid inconsistent states.

<img src="https://github.com/Oeffis/Oeffis/assets/53478084/b2eda78f-c977-41cd-b83d-7eb07c6f2c4e" alt="drawing" width="200"/>

**Comment by AconexOfficial** [comment]
Time spent: 1 hour 30 minutes

**Comment by AconexOfficial** [comment]
Also added the faint indicating arrows to route options swiper.
+ Added fix for scrolling in favorites, so the whole screen is swipeable instead of only the items in the list.

**Comment by AconexOfficial** [comment]
Time spent: 2 hours

Various improvements and UX changes, aswell as small bug fixes

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

Resolve merge conflicts, change spacing for radio bar, replaces header in live navigation with header component
