### ISSUE TITLE
Setup Dependabot

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#39]
DependaBot helps to keep dependencies up to date.
This project might require admin privileges.

- [x] add DependaBot to the project
- [x] configure DependaBot for backend
- [x] configure DependaBot for frontend
- [x] configure DependaBot to automatically open Pas

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

**Comment by timvahlbrock** [comment]
Time spent: 2 hours

**Comment by JaJako** [comment]
Dunno if the current Dependabot approach is that optimal having such a load of PRs/branches every day and one commit per updated dependencies (obscures the actual relevant commits on main a bit). 
What about doing the Dependabot checks weekly all together in a single commit? (But that's just my opinion.)

**Comment by timvahlbrock** [comment]
> Dunno if the current Dependabot approach is that optimal having such a load of PRs/branches every day and one commit per updated dependencies (obscures the actual relevant commits on main a bit).
> What about doing the Dependabot checks weekly all together in a single commit? (But that's just my opinion.)

You're absolutely right, I'm not too happy with that either. I somewhat underestimated the amount of PRs that this would cause, but wouldn't worry about the amount of commits too much. We could definitely reduce the schedule to weekly. However, grouping updates is currently under development: https://github.com/dependabot/dependabot-core/issues/1190 . So we basically can 

1. reduce the schedule, but still live with approximately the same amount of PRs
2. wait for grouped updates to be supported, disable automatic updates for now, as long as they aren't security related
3. get automatic merging going, still same amount of PRs, but less manual work for us

Can we maybe get some more @Oeffis/core-team opinions on this?

**Comment by timvahlbrock** [comment]
Alternatively, we could also switch do renovate, which already supports grouping dependency updates.

**Comment by timvahlbrock** [comment]
I tried to fix the auto merging in #142 by providing Dependabot with an own token for merging.

**Comment by timvahlbrock** [comment]
Time spent: 3 hours

**Comment by timvahlbrock** [comment]
I disabled dependabot version updates for now. Dependabot will now only create merge requests for security relevant versions. @Oeffis/core-team I'm sorry about the amount of messages and inconsistencies of decisions regarding this topic.

**Comment by Paulomart** [comment]
Time spent: 1 hour
