### ISSUE TITLE
Improve Leaflet integration

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#399]
~~The current library used for leaflet integration, `react-leaflet` is not very well maintained and has bugs. It should be refactored out.~~

Leaflet integration currently is buggy and needs to be improved.

**Comment by timvahlbrock** [comment]
Time spent: 6 hours

Spent on:
- debugging, investigation
- uncommitted changes

**Comment by timvahlbrock** [comment]
Time spent: 2,5 hours

Spent on:

+ 6cec692642da340cac55d063dd88cde9c206015b implement abstraction layer on top of leafletmapcontainer to listen to center/zoom/bounds changes
+ cf0e4ad6d01719d2a78f2e1f3312903d566a9226 fix map sometimes only loading one tile
+ 71eddcafb8d9c506bed51399af3f1cacb37544d6 make map bound locations

**Comment by Paulomart** [comment]
Time spent: 30 minutes

Reviews
