### ISSUE TITLE
Project vision (presentation)

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#40]
/We are charged to define (and present) our vision for the project.

- What is our goal/vision?
- What is the "rationale for existence" (why developing this)?
- How do we approach the project (organisation/management)?
  - structure of features
- What are our substantive objectives and how do we plan achieving them?
  - Use Cases
  - Layout
  - ...
=> Target Group: externals

Subtasks:
- [x] #42
- [x] #145
- [x] Organize pitch
- [x] Prepare to present

**Comment by timvahlbrock** [comment]
@WConen  In how much detail do you want the presentation to be? Is there a specification of minutes the presentation should take?

**Comment by timvahlbrock** [comment]
I propose that we make the statistics and predictions one of the main goals of our projects, as those make our project unique.

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by JaJako** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
@Oeffis/core-team 
If you have spent some time preparing yourself for the project vision presentation, please add your time spent in here.

**Comment by timvahlbrock** [comment]
Time spent: 30minutes

**Comment by timvahlbrock** [comment]
Time spent: 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 30 minutes

**Comment by Paulomart** [comment]
Time spent: 30 minutes

**Comment by JaJako** [comment]
As work is completed, the issue is closed now.

**Comment by Escowei98** [comment]
Time spent: 30 minutes
