### ISSUE TITLE
Project Vision: Find and set a date.

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#42]
We need to find a date to hold the presentation about our project vision. Ideally this should be within the current semester (June/Juli/August). Everyone should be able to join the presentation (taking holidays into account).

**Comment by timvahlbrock** [comment]
depends on #38

**Comment by Paulomart** [comment]
Präsentation (alle)
Geplant: 07.07.2023
https://teamup.com/ksdx97bkjtwaffvv8t/events/1537585432
Who: alle
