### ISSUE TITLE
Presentation for 28.11.

### ISSUE THREAD

**Issue by LaraBiss** [Oeffis/Oeffis#439]
Short presentation about the current state of the project

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by JaJako** [comment]
Time spent: 30 minutes

**Comment by timvahlbrock** [comment]
Time spent: 30 minutes

**Comment by Paulomart** [comment]
Time spent: 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 30 minutes
