### ISSUE TITLE
Global Stats Notebook

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#462]

**Comment by timvahlbrock** [comment]
Time spent: 3 hours

Spent on:
- Prepping
- Importing the latest DB Snapshot

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

Spent on:
- Trying to import latest DB Snapshot, discarded

**Comment by timvahlbrock** [comment]
Time spent: 2 hours

Spent on:
- Query construction

**Comment by timvahlbrock** [comment]
Time spent: 6 hours

Spent on:
+ 193b02dd8ff36d30a7ba591afab190f48e374cb5 wip stash
+ 6ff6c9020b97608712a80c8dc2320a9852f77810 wip create typescript global stats script

**Comment by timvahlbrock** [comment]
Time spent: 2 hours

Spent on:
+ 36415fc53a525a65ff3a34976ad97fb999c882f3 Add stats endpoint to backend

**Comment by timvahlbrock** [comment]
Time spent: 5 hours

Spent on:
+ 4524720646b084c769c5f8a5dbb6d40d16bf68b1 Add stats page to frontend (empty for now)
+ 4769a8cc4ad704eb8807d42d6a8f6a6fcff409ac Show stats as json on stats page
+ cdbf6baa1ef901415ba3dee87f684bd34ff68ac8 cache stats
+ c845d52e6538d542ba27084a59e73f48c3b76f61 Write/read stats cach from file system
+ 7fafc101d21db6d7f0e47514ccc58631d3801854 Prepare table for stats
+ 9f8ba9d46da974c8857cbf53e3f6c014908eb561 Implement comprehensive stat list
+ f421b7ef36d4059091cfdeca54d41985ace83e4d fix linting error

**Comment by JaJako** [comment]
Time spent: 30 minutes

Reviewing PR.

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

Spent on:
- Adding delay stats for the last 24 hours
