### ISSUE TITLE
Notify User at next step if better route is available

### ISSUE THREAD

**Issue by Escowei98** [Oeffis/Oeffis#496]

**Comment by Escowei98** [comment]
Time spent: 3 hours

**Comment by Escowei98** [comment]
Time spent: 1 hour 30 minutes

**Comment by Escowei98** [comment]
Time spent: 30 minutes

**Comment by Escowei98** [comment]
Time spent: 8 hours

**Comment by Escowei98** [comment]
Left to do:

- style modal with Recommended Journey Informations
- fix hook error
- blacklist functionality

**Comment by Escowei98** [comment]
Time spent: 5 hours

**Comment by Escowei98** [comment]
Left to do:

- find more efficient way to look for better routes

**Comment by Escowei98** [comment]
Time spent: 1 hour

**Comment by LaraBiss** [comment]
Time spend: 30 minutes 

Spent on: review

**Comment by LaraBiss** [comment]
Time spent: 30 minutes
Spent on: review
