### ISSUE TITLE
Discuss Show'n Tell Poster Content

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#499]
Needed areas of discussion in top-down order:
- [x] Subtitle to the project title
- [x] All full names + abbreviation of current degree
- [x] Initial Problems to solve + Photo
- [x] Ideas and Concept / Approach of solving the problems + Photo
- [x] Technical Implementation
- [ ] 2 more photos
- [x] Studmails
- [ ] Supervisor information

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by dkrakau** [comment]
Time spent: 1 hour

**Comment by JaJako** [comment]
Time spent: 30 minutes

Some general discussions about poster's content / pictures.

**Comment by AconexOfficial** [comment]
Time spent: 4 hours

**Comment by dkrakau** [comment]
Time spent: 4 hours

**Comment by LaraBiss** [comment]
Time spend: 30 minutes

Spend on: general discussion & photo

**Comment by LaraBiss** [comment]
Time spent: 30 minutes

Spend on: general discussion & photo

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 2 hours
Spend on: 
- pictures for route planner, details & options
- help resolve merge conflicts
