### ISSUE TITLE
Determine Technology Stack

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#5]
Discussed in https://github.com/Oeffies/Oeffies/discussions/3

**Comment by timvahlbrock** [comment]
set in meeting on 16.05.2023 (see wiki). succeeded by #16

**Comment by JaJako** [comment]
Time spent: 1 hours

**Comment by JaJako** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by Escowei98** [comment]
Time spent: 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 30 minutes
