### ISSUE TITLE
Create elevator pitch

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#508]
```[tasklist]
### Tasks
- [x] Create slides
- [x] Create text
```

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

Assembling ideas for slides and images

**Comment by dkrakau** [comment]
Time spent: 1 hour

Assembling ideas for slides and images

**Comment by JaJako** [comment]
Time spent: 1 hour

Preparing elevator pitch content + slides.

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

Discussing elevator pitch

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 2 hours

Preparing elevator pitch speech & discuss

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 1 hour 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

Refining text and practice

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

Practicing

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

Created a standee with a QR-Code to the app for out Show and Tell booth

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

Practiceing
