### ISSUE TITLE
Add spent time to done issues

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#51]

**Comment by timvahlbrock** [comment]
@Paulomart as #52 is fixed, can I start this now?

**Comment by Paulomart** [comment]
Yes.

**Comment by timvahlbrock** [comment]
Notice has been added to all issues. Adding the remaining time is now up to each @Oeffis/core-team member.

**Comment by JaJako** [comment]
Time spent: 1 hours
