### ISSUE TITLE
Create Show and Tell video

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#545]

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

Gather stock footage, create project, rough structure

**Comment by LaraBiss** [comment]
Time spent: 1 hour

Spend on: 
- make videos from all features

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by AconexOfficial** [comment]
Time spent: 4 hours

**Comment by AconexOfficial** [comment]
Link to the video: https://youtu.be/GZgpK4ytL7o?si=6TUykwgOvXgW62ZM
