### ISSUE TITLE
Show And Tell

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#565]

**Comment by timvahlbrock** [comment]
Time spent: 4 hours 30 minutes

**Comment by JaJako** [comment]
Time spent: 4 hours 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 4 hours 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 4 hours 30 minutes

**Comment by dkrakau** [comment]
Time spent: 4 hours 30 minutes
