### ISSUE TITLE
Determine Work Process

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#6]
Discussed in https://github.com/Oeffies/Oeffies/discussions/4

**Comment by timvahlbrock** [comment]
Process was documented in wiki

**Comment by JaJako** [comment]
Time spent: 5 hours

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by Escowei98** [comment]
Time spent: 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 3 hours
