### ISSUE TITLE
Enable `merge_groups`

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#61]
See https://docs.github.com/de/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

**Comment by Paulomart** [comment]
Time spent: 1 hour

**Comment by Paulomart** [comment]
Time spent: 1 hour

**Comment by timvahlbrock** [comment]
@Paulomart is this done?

**Comment by timvahlbrock** [comment]
I'm gonna close this for now. Reopen if this isn't done
