### ISSUE TITLE
Design App Icon

### ISSUE THREAD

**Issue by LaraBiss** [Oeffis/Oeffis#65]
- [x] Design app icon drafts
- [x] Discussion for voting
- [x] Refine chosen app icon

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 1 hour 

Spend on:
- sketching

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by AconexOfficial** [comment]
Time spent: 2 hours

**Comment by AconexOfficial** [comment]
TIme spent: 30 minutes
