### ISSUE TITLE
Determine Time Tracking Solution

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#7]
Discussed in https://github.com/Oeffies/Oeffies/discussions/2

**Comment by timvahlbrock** [comment]
set in meeting on 16.05.2023 (see wiki). succeeded by #19

**Comment by timvahlbrock** [comment]
No time spent on this issue, as it was succeeded by #19

**Comment by JaJako** [comment]
> No time spent on this issue, as it was succeeded by https://github.com/Oeffis/Oeffis/issues/19

Meaning time spent on research of time tracking solutions (in general) should be tracked on #19, too?

**Comment by JaJako** [comment]
Time spent: 1 hours
