### ISSUE TITLE
Input for start and destination

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#74]
~~- [ ] Input field for start station (as a dropdown list)~~ Will be reworked as proposed inside the general structure meeting
~~- [ ] Input field for destination (as a dropdown list)~~ Will be reworked as proposed inside the general structure meeting
- [x] Button to confirm both inputs
- [x] Data collection from input fields
- [x] Route-details are saved in query parameters

**Comment by LaraBiss** [comment]
Would rather be an editable dropdown list than an input field to show possible stations etc. .

**Comment by AconexOfficial** [comment]
Time spent: 2 hours

Spent on:

Created container for route planning inputs
Created provisoric input fields for start and destination
Created submit button, putting the inputs into url params
Implemented into the home.tsx for visual purposes

Commits:
9e485b4 Created container for inputs and confirm button. Also added to home screen

**Comment by AconexOfficial** [comment]
Time spent: 1 hour 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 1 hour 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

Trying to get the SearchableDropdown to work. Still having difficulties to sort out with react-native.

**Comment by timvahlbrock** [comment]
Are you actually using react-native? If so, please don't, as we are building an ionic based app, which has native-like components already integrated (see https://ionicframework.com/docs/api/input). There is no specific "input with autocomplete", but you could use a combination of ion-searchbar and maybe something like ion-popover.

**Comment by AconexOfficial** [comment]
At first I didn't intend on trying react-native, but I thought I'd give it a try.
Yeah, it seems like I'll have to create a custom SearchableDrowpdown with those ionic components

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

Spent on:
- Review, Feedback

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

Small changes to structure

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

Spent on:
- Pair Programming with @AconexOfficial to resolve the requested changes of the review
