### ISSUE TITLE
Show map

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#75]
- [x] Choose fitting maps API
- [x] Implement map into frontend

**Comment by timvahlbrock** [comment]
Known limitation of current implementation:

- map marker is not currently shown when app is deployed by docker image. Wether this is relevant needs to be determined in #77 
- the map tiles are currently loaded from OpenStreetMap servers at usage. We should think about caching or storing them locally.
- the map is currently initialised to show our university. Maybe #73 can address initialising the map to the location of the user

**Comment by timvahlbrock** [comment]
Time spent: 3 hours

**Comment by JaJako** [comment]
Are we capturing time spent reviewing/testing a PR on the linked issue?

**Comment by timvahlbrock** [comment]
> Are we capturing time spent reviewing/testing a PR on the linked issue?

Yes
