### ISSUE TITLE
Determine Better Name

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#8]
Discussed in https://github.com/Oeffies/Oeffies/discussions/1

**Comment by timvahlbrock** [comment]
Name was for now set to "Oeffis"

**Comment by timvahlbrock** [comment]
@core-team members each needs to add the time spent on this issue.

**Comment by timvahlbrock** [comment]
Time spent: 1 hours

**Comment by Paulomart** [comment]
Time spent: 1 hours

**Comment by JaJako** [comment]
Time spent: 1 hours

**Comment by JaJako** [comment]
Time spent: 1 hours

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by LaraBiss** [comment]
Time spent: 30 minutes
