### ISSUE TITLE
Add button to route view to add or remove route as favourite.

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#92]
- [x] Use the context to get the favourite service
- [x] Detect if the currently open route is already saved
- [x] Allow to toggle favourite state

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

Spent on:

+ c66a518fc5e7c71625f0281b4f6d13156d642638 (WIP) add visualization of favourite locations
+ d6f8776056830c8cab6fbb508326cb9bc1e0a55d fix hook error
+ a83bb67ebbf63f58622b299b705fadac8efc845f set trip when clicking
+ bc95c19d53b600aaa6b19fc5097b19dec1f123f1 prevent adding trips that are already favorites

**Comment by timvahlbrock** [comment]
Time spent: 1,5 hours

Spent on:
+ 6df61672ba04d0f09f7cbb98eee362053926ff91 implement reorder of favorites
+ c3eec777ad2cfa86bd82c43f77e60e8b5f54102f tidy trip favorites
+ e2690888f5d5d8ab9111ad00534e30c7485826f4 tidy trip favorites
+ 310d7eba4b1d1cd16d5ca4d67a0a4d4227802539 fix linting errors

**Comment by timvahlbrock** [comment]
Time spent: 2 hours

Spent on:

+ 1ad068faa896bb9b2e36f7272d2296877c2d8d34 implement useLocationById hook
+ ba1f20b0358e5fcc8a74f9f18440121b0c1d62a5 implement useNullableLocationById hook
+ 3ad31e6be5bfd2f6a28c602a13cda74e8c14f1dc simplify return type of hooks
+ 40ff097c2e5f51d57d70b514adc6420476015dd1 (WIP) fix hook
+ 0d7b2076261ebcb3f2a2f36095fe54b36c6a1bf6 (WIP) adapt RoutePlanner

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

Spent on:
+ c5f41a0a985266e552d0208846def137f883042d UI touchups
+ 0f9998312bd9278766ffd4f8474cd217bad3535b fix abort error

**Comment by timvahlbrock** [comment]
Time spent: 30 minutes

Spent on:
+ dc0a7b602f710cfb50ccdf6f54072c56a3fb60e5 Fix favourites vs favorite typo
+ 86c5243d7663f3fe75cac74415a193765582f695 fix 'is not a keyword' error
+ 96525aee820e2c483cfef3aea5d8617b61ac830f fix frontend tests
