### ISSUE TITLE
Expand route view to include departure time in query and url parameters

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#98]
- [x] Expand the route view to include selected date as parameter in journey query
- [x] Encode date parameters in url of route view

**Comment by JaJako** [comment]
Some input element to interpret selected date as "arrival" and not (as per default) "departure" time is missing in Frontend (Route Planner).

**Comment by JaJako** [comment]
Time spent: 3 hours 30 minutes

Implementing url parameter for departure time (and dealing with some problems regarding validation etc.).

**Comment by JaJako** [comment]
Time spent: 4 hours 30 minutes

Finishing up basic implementation + improving implementation of departureTime states.

**Comment by JaJako** [comment]
Time spent: 1 hour

Fixing dates are not being deserialized from String to Date in Backend (activating transformation and validation in Backend).

**Comment by JaJako** [comment]
Time spent: 2 hours 30 minutes

Improving states implementation (use hooks) + open PR.
